BEGIN TRANSACTION;
CREATE TABLE `settings` (
	`settings_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`key`	TEXT,
	`value`	TEXT
);
CREATE TABLE "queue" (
	`job_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`payload`	TEXT NOT NULL,
	`status`	INTEGER NOT NULL,
	`message`	TEXT,
	`rpm_url`	TEXT
);
CREATE TABLE "packages" (
	`pkg_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL,
	`version`	TEXT NOT NULL,
	`release`	INTEGER NOT NULL DEFAULT 0
);
COMMIT;
